server:
  port: 8083

spring:
  application:
    name: toolscheduler
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: toolscheduler-consumer-group

kafka:
  topics:
    scan-job: "scan-job"
    scan-request: "scan-request"

logging:
  level:
    org:
      apache:
        kafka: ERROR
      springframework:
        kafka: ERROR
    kafka: ERROR
